name: Build
on:
  push:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Build with Buildozer
      #   uses: ArtemSBulgakov/buildozer-action@v1
      #   id: buildozer
      #   with:
      #     workdir: .
      #     buildozer_version: stable

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: package
      #     path: ${{ steps.buildozer.outputs.filename }}
      - name: Build with Buildozer
        run: |
          pip3 install --user --upgrade buildozer
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 virtualenv 
          export PATH=$PATH:~/.local/bin/
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
