name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure buildozer.spec
        run: |
          buildozer init
          # Modify buildozer.spec as needed

      - name: Build APK
        run: |
          buildozer android debug
          ls -lh bin
          
      - name: Accept Android SDK Licenses
        run: echo "y" | sdkmanager --licenses

      - name: Install Android Build Tools
        run: sdkmanager "build-tools;30.0.3"  # Replace with the version you need

      - name: Install aidl Tool
        run: sdkmanager "build-tools;30.0.3"  # Use the same version as above
